SET LINES 102
SET PAGES 2000
SET NUMFORMAT 999999.99
BREAK ON REPORT ON CAT_PRD_CD

TTITLE CENTER 'DEPOT: '&&SC_CD' BATCH WISE STOCK' SKIP2

SPOOL ON 

SELECT  
    TO_CHAR(B.CAT_CD || B.PRD_CD) AS CAT_PRD_CD, 
    COUNT(*) OVER (PARTITION BY B.CAT_CD || B.PRD_CD) AS D_count,
    SUBSTR(C.PROD_NM, 1, 30) AS NAME, 
    B.B_NO, 
    SUM(B.RV_QTY) AS RV_QTY1, 
    SUM(B.RV_BAL) AS STK_QTY, 
    SUM(B.RV_BAL / D.MST_PK) AS PETTY, 
    SUM(B.RV_QTY - B.RV_BAL) AS DIFF 
FROM 
    INV.FG_RV1 A, 
    INV.FG_RV2 B, 
    SCENT.INV_PROD C, 
    SCENT.PROD_RATE D 
WHERE 
    A.RV_NO = B.RV_NO 
    AND A.LOC_CD = '&&SC_CD' 
    AND (B.RV_BAL) > '0' 
    AND B.CAT_CD = C.CAT_CD 
    AND B.PRD_CD = C.PRD_CD 
    AND B.TYP_CD = C.TYP_CD 
    AND A.LOC_CD = B.LOC_CD 
    AND B.CAT_CD = D.CAT_CD 
    AND B.PRD_CD = D.PRD_CD 
    AND B.TYP_CD = D.TYP_CD 
    AND A.RV_DT BETWEEN '01-JAN-19' AND '31-DEC-27' 
    AND B.CAT_CD > '0' 
    AND A.DIV_CD = '1' 
    AND B.TYP_CD = '09' 
    AND A.RV_TYPE NOT IN ('0')
GROUP BY 
    B.CAT_CD || B.PRD_CD, 
    C.PROD_NM, 
    B.B_NO, 
    B.RV_QTY, 
    B.RV_BAL
HAVING 
    (B.RV_QTY - B.RV_BAL) > 0 
ORDER BY 
    D_count DESC, B.CAT_CD || B.PRD_CD 
/



SELECT  
    TO_CHAR(B.CAT_CD || B.PRD_CD) AS CAT_PRD_CD, 
    COUNT(*) OVER (PARTITION BY B.CAT_CD || B.PRD_CD) AS D_count,
    SUBSTR(C.PROD_NM, 1, 30) AS NAME, 
    B.B_NO, 
    SUM(B.RV_QTY) AS RV_QTY1, 
    SUM(B.RV_BAL) AS STK_QTY, 
    SUM(B.RV_BAL / D.MST_PK) AS PETTY, 
    SUM(B.RV_QTY - B.RV_BAL) AS DIFF 
FROM 
    INV.FG_RV1 A, 
    INV.FG_RV2 B, 
    SCENT.INV_PROD C, 
    SCENT.PROD_RATE D 
WHERE 
    A.RV_NO = B.RV_NO 
    AND A.LOC_CD = '&&SC_CD' 
    AND (B.RV_BAL) > '0' 
    AND B.CAT_CD = C.CAT_CD 
    AND B.PRD_CD = C.PRD_CD 
    AND B.TYP_CD = C.TYP_CD 
    AND A.LOC_CD = B.LOC_CD 
    AND B.CAT_CD = D.CAT_CD 
    AND B.PRD_CD = D.PRD_CD 
    AND B.TYP_CD = D.TYP_CD 
    AND A.RV_DT BETWEEN '01-JAN-19' AND '31-DEC-25' 
    AND B.CAT_CD > '0' 
    AND A.DIV_CD = '2' 
    AND B.TYP_CD = '09' 
    AND A.RV_TYPE NOT IN ('0')
GROUP BY 
    B.CAT_CD || B.PRD_CD, 
    C.PROD_NM, 
    B.B_NO, 
    B.RV_QTY, 
    B.RV_BAL
HAVING 
    (B.RV_QTY - B.RV_BAL) > 0 
ORDER BY 
    D_count DESC, B.CAT_CD || B.PRD_CD 
/


SPOOL OFF
ED ON.LST
