---SELECTED PRODUCT BILL OF ALL PARTIES

SET VER OFF

SET LINES 175
SET PAGES 5000
BREAK ON REPORT ON BILL_NO
COMPUTE SUM OF NET_QTY ON REPORT

SPOOL ON

SELECT A.SC_CD, A.FP_ID, A.DIST_CD||A.THA_CD||A.UN_CD||A.CL_ID CL_ID, INITCAP(SUBSTR(C.CL_NM,1,18)) CL_NM, A.BILL_NO, A.DELI_DT, A.SALE_NET, A.SALE_CD, D.CAT_CD||D.PRD_CD P_CODE,
INITCAP(SUBSTR(E.PROD_NM,1,20)) PROD_NM, D.FLAT_RT BILL_RT, D.PRO_QTY, D.RT_QTY, D.PRO_QTY - D.RT_QTY NET_QTY, D.SALE_GR, D.SALE_NET
	FROM SCENT.BILL_MAS A,SCENT.FP_MGR B,SCENT.CL_INFO C, SCENT.BILL_DET D, SCENT.INV_PROD E
	WHERE A.SC_CD='&&SC_CD'AND
	A.DELI_DT BETWEEN '&DATE1' AND '&DATE2' AND
	A.BILL_NO = D.BILL_NO AND
	A.SC_CD=B.SC_CD AND
	A.SC_CD=C.SC_CD AND
	A.SC_CD=D.SC_CD AND
	A.FP_ID=B.FP_ID AND
	A.DIST_CD=C.DIST_CD AND
	A.THA_CD=C.THA_CD AND
	A.UN_CD=C.UN_CD AND
	A.CL_ID=C.CL_ID AND 
	A.FL_MVH='1' AND
	D.CAT_CD||D.PRD_CD IN ('&PROD1','&PROD2') AND
	D.TYP_CD=E.TYP_CD AND 
	D.CAT_CD=E.CAT_CD AND
	D.PRD_CD=E.PRD_CD 
	ORDER BY CL_ID, A.BILL_NO

/



SPOOL OFF

ED ON.LST
