
SET LINES 110
SET PAGES 15000
BREAK ON CL_ID ON REPORT
---COMPUTE SUM OF SALE_NET ON CL_ID


SPOOL ON

SELECT DISTINCT A.SC_CD, A.FP_ID, A.DIST_CD||A.THA_CD||A.UN_CD||A.CL_ID CL_ID, INITCAP(SUBSTR(C.CL_NM,1,20)) CL_NM, INITCAP(SUBSTR(regexp_replace(C.CL_ADDR, '[/0-9]', ''),1,20)) CL_ADDR, C.TEL, A.BILL_NO, A.DELI_DT, A.SALE_NET, A.SALE_CD
	FROM SCENT.BILL_MAS A,SCENT.FP_MGR B,SCENT.CL_INFO C, SCENT.FP_BASE D
	WHERE A.SC_CD='&SC_CD'AND
	A.SC_CD=B.SC_CD AND
	A.SC_CD=C.SC_CD AND
	A.SC_CD=D.SC_CD AND
	A.FP_ID=B.FP_ID AND
	A.DIST_CD=C.DIST_CD AND
	A.THA_CD=C.THA_CD AND
	A.UN_CD=C.UN_CD AND
	A.CL_ID=C.CL_ID AND
	A.DELI_DT BETWEEN '01JAN24' AND '02JAN24' AND
	A.FL_MVH='1' AND
	A.FL_MVH=D.FL_MVH AND
	A.RMBS_CD=D.RMBS_CD AND
	A.FMBS_CD=D.FMBS_CD AND
	A.SALE_CD IN('IC','WM','WO','RC')
	ORDER BY CL_ADDR, CL_NM, A.DIST_CD||A.THA_CD||A.UN_CD||A.CL_ID, A.BILL_NO

/




SPOOL OFF

ED ON.LST






