SET LINE 118
SET PAGES 5000
SET NUM FORMAT 99,000.00

SPOOL ON

accept DT1 char prompt 'FIRST DATE :'
accept DT2 char prompt 'LAST DATE :'
accept FL char prompt 'DIVISION:'
accept sc char prompt 'sc:'

SET VER OFF


SELECT Z.BILL_NO,Z.DELI_DT,Z.RTN_NO,Z.RTN_DT,(Z.CAT_CD||Z.PRD_CD)CODE,Z.PRD_NM,Z.BILL_QTY,Z.BNS_QTY,Z.RTN_QNT,Z.GAIN,(Z.BNS_QTY-Z.GAIN)DIFF FROM
(SELECT X.BILL_NO,X.DELI_DT,X.RTN_NO,X.RTN_DT,X.CAT_CD,X.PRD_CD,SUBSTR((Y.PROD_NM),1,20)PRD_NM,SUM(PR_QTY)BILL_QTY,SUM(BNS)BNS_QTY,SUM(QTY)RTN_QNT,SUM(GAIN)GAIN FROM
(SELECT A.BILL_NO,F.DELI_DT,A.RTN_NO,A.RTN_DT,B.CAT_CD,B.PRD_CD,SUM(D.PRO_QTY)PR_QTY,SUM(C.BONUS_QNT)BNS,SUM(B.RTN_QTY)QTY,SUM(C.BONUS_QNT/D.PRO_QTY*B.RTN_QTY)GAIN FROM SCENT.RTN_MAS A,SCENT.RTN_DET B,SCENT.BONUS_SALE C,SCENT.BILL_DET D,
SCENT.BILL_MAS F
WHERE A.SC_CD=B.SC_CD
AND A.RTN_NO=B.RTN_NO
AND A.SC_CD='&sc'
AND A.BILL_NO=C.BILL_NO
AND A.BILL_NO=F.BILL_NO
AND D.BILL_NO=F.BILL_NO
AND A.SC_CD=C.SC_CD
AND B.SC_CD=C.SC_CD
AND A.SC_CD=F.SC_CD
AND C.SC_CD=F.SC_CD
AND B.SC_CD=F.SC_CD
AND B.CAT_CD=C.CAT_CD
AND B.PRD_CD=C.PRD_CD
AND A.CANCL IS NULL
AND F.CANCL IS NULL
AND A.RTN_DT BETWEEN '&DT1' AND '&DT2'
AND B.CAT_CD=D.CAT_CD
AND B.PRD_CD=D.PRD_CD
AND B.SC_CD=D.SC_CD
AND C.CAT_CD=D.CAT_CD
AND C.PRD_CD=D.PRD_CD
AND C.Sc_CD=D.Sc_CD
AND A.FL_MVH='&FL'
AND A.Sc_CD=D.SC_CD
AND A.BILL_NO=D.BILL_NO
GROUP BY A.BILL_NO,F.DELI_DT,A.RTN_NO,A.RTN_DT,B.CAT_CD,B.PRD_CD)X,SCENT.INV_PROD Y WHERE X.CAT_CD=Y.CAT_CD
AND X.PRD_CD=Y.PRD_CD
AND Y.TYP_CD='09'
GROUP BY X.BILL_NO,X.DELI_DT,X.RTN_NO,X.RTN_DT,X.CAT_CD,X.PRD_CD,Y.PROD_NM)Z,
(SELECT A.CAT_CD,A.PRD_CD,SUBSTR((B.PROD_NM),1,40)PRD_NM,0 GAIN FROM INV.FG_RV2 A,SCENT.INV_PROD B
WHERE A.RV_NO IN(SELECT RV_NO FROM INV.FG_RV1 WHERE RV_DT BETWEEN '&DT1' AND '&DT2'
AND DIV_CD='&FL' AND RV_TYPE='04' AND LOC_CD='&sc') AND A.LOC_CD='&sc'
AND A.CAT_CD=B.CAT_CD
AND A.PRD_CD=B.PRD_CD
AND A.TYP_CD=B.TYP_CD
AND A.TYP_CD='09'
GROUP BY A.CAT_CD,A.PRD_CD,B.PROD_NM)X WHERE Z.CAT_CD=X.CAT_CD(+)
AND Z.PRD_CD=X.PRD_CD(+)
ORDER BY Z.BILL_NO,Z.DELI_DT
/

SELECT DISTINCT Z.CAT_CD||Z.PRD_CD,Z.PRD_NM,Z.BILL_QTY,Z.BNS_QTY,Z.RTN_QNT,Z.GAIN,(Z.BNS_QTY-Z.GAIN)DIFF FROM
(SELECT X.CAT_CD,X.PRD_CD,SUBSTR((Y.PROD_NM),1,20)PRD_NM,SUM(PR_QTY)BILL_QTY,SUM(BNS)BNS_QTY,SUM(QTY)RTN_QNT,SUM(GAIN)GAIN FROM
(SELECT A.BILL_NO,F.DELI_DT,A.RTN_NO,A.RTN_DT,B.CAT_CD,B.PRD_CD,SUM(D.PRO_QTY)PR_QTY,SUM(C.BONUS_QNT)BNS,SUM(B.RTN_QTY)QTY,SUM(C.BONUS_QNT/D.PRO_QTY*B.RTN_QTY)GAIN FROM SCENT.RTN_MAS A,SCENT.RTN_DET B,SCENT.BONUS_SALE C,SCENT.BILL_DET D,
SCENT.BILL_MAS F
WHERE A.SC_CD=B.SC_CD
AND A.RTN_NO=B.RTN_NO
AND A.SC_CD='&sc'
AND A.BILL_NO=C.BILL_NO
AND A.BILL_NO=F.BILL_NO
AND D.BILL_NO=F.BILL_NO
AND A.SC_CD=C.SC_CD
AND B.SC_CD=C.SC_CD
AND A.SC_CD=F.SC_CD
AND C.SC_CD=F.SC_CD
AND B.SC_CD=F.SC_CD
AND B.CAT_CD=C.CAT_CD
AND B.PRD_CD=C.PRD_CD
AND A.CANCL IS NULL
AND F.CANCL IS NULL
AND A.RTN_DT BETWEEN '&DT1' AND '&DT2'
AND B.CAT_CD=D.CAT_CD
AND B.PRD_CD=D.PRD_CD
AND B.SC_CD=D.SC_CD
AND C.CAT_CD=D.CAT_CD
AND C.PRD_CD=D.PRD_CD
AND C.Sc_CD=D.Sc_CD
AND A.FL_MVH='&FL'
AND A.Sc_CD=D.SC_CD
AND A.BILL_NO=D.BILL_NO
GROUP BY A.BILL_NO,F.DELI_DT,A.RTN_NO,A.RTN_DT,B.CAT_CD,B.PRD_CD)X,SCENT.INV_PROD Y WHERE X.CAT_CD=Y.CAT_CD
AND X.PRD_CD=Y.PRD_CD
AND Y.TYP_CD='09'
GROUP BY X.CAT_CD,X.PRD_CD,Y.PROD_NM)Z,
(SELECT A.CAT_CD,A.PRD_CD,SUBSTR((B.PROD_NM),1,40)PRD_NM,0 GAIN FROM INV.FG_RV2 A,SCENT.INV_PROD B
WHERE A.RV_NO IN(SELECT RV_NO FROM INV.FG_RV1 WHERE RV_DT BETWEEN '&DT1' AND '&DT2'
AND DIV_CD='&FL' AND RV_TYPE='04' AND LOC_CD='&sc') AND A.LOC_CD='&sc'
AND A.CAT_CD=B.CAT_CD
AND A.PRD_CD=B.PRD_CD
AND A.TYP_CD=B.TYP_CD
AND A.TYP_CD='09'
GROUP BY A.CAT_CD,A.PRD_CD,B.PROD_NM)X WHERE Z.CAT_CD=X.CAT_CD(+)
AND Z.PRD_CD=X.PRD_CD(+)
ORDER BY Z.CAT_CD||Z.PRD_CD
/


SPOOL OFF
ED ON.LST