SET NUMFORMAT 99999.99


SET LINES 100
SET PAGES 500

SET VER OFF

----------------------------BONUS_RV
DROP TABLE BONUS_RV
/

SPOOL ON


CREATE TABLE BONUS_RV AS
SELECT DISTINCT 
A.CAT_CD,
A.PRD_CD,
D.PRO_QTY BILL_QTY,
A.RTN_QTY,
SUM((C.BONUS_QNT/D.PRO_QTY)*A.RTN_QTY)BONUS_QNT,0 RV_QTY
 FROM SCENT.RTN_DET A,
SCENT.RTN_MAS B,
SCENT.BONUS_SALE C,
SCENT.BILL_DET D
WHERE 
A.RTN_NO=B.RTN_NO AND 
B.BILL_NO=C.BILL_NO AND 
B.BILL_NO=D.BILL_NO AND 
C.BILL_NO=D.BILL_NO AND 
C.CAT_CD=D.CAT_CD AND 
A.CAT_CD=D.CAT_CD AND 
A.PRD_CD=D.PRD_CD AND 
C.PRD_CD=D.PRD_CD AND
A.TYP_CD=D.TYP_CD AND 
B.RTN_NO=A.RTN_NO AND
A.TYP_CD='09' 
AND A.SC_CD='&&SC_CD'
AND C.SC_CD='&&SC_CD'
AND D.SC_CD='&&SC_CD'
AND B.SC_CD='&&SC_CD'
AND B.RTN_DT BETWEEN '&&DATE1' AND '&&DATE2' 
AND B.CANCL IS NULL
GROUP BY A.CAT_CD,A.PRD_CD,D.PRO_QTY,A.RTN_QTY
/
CREATE TABLE K_BONUS_RV AS
SELECT DISTINCT A.CAT_CD,A.PRD_CD,SUM(D.PRO_QTY)BILL_QTY,SUM(A.RTN_QTY)RTN_QTY,
SUM((C.BONUS_QNT/D.PRO_QTY)*A.RTN_QTY)BONUS_QNT,0 RV_QTY
FROM SCENT.RTN_DET A,SCENT.RTN_MAS B,SCENT.BONUS_SALE C,SCENT.BILL_DET D
WHERE A.RTN_NO=B.RTN_NO AND B.BILL_NO=C.BILL_NO AND
B.BILL_NO=D.BILL_NO AND C.BILL_NO=D.BILL_NO AND C.CAT_CD=D.CAT_CD AND
A.CAT_CD=D.CAT_CD AND A.PRD_CD=D.PRD_CD AND C.PRD_CD=D.PRD_CD AND
A.TYP_CD=D.TYP_CD AND B.RTN_NO=A.RTN_NO AND A.TYP_CD='09'
AND A.SC_CD='&&SC_CD'
AND C.SC_CD='&&SC_CD'
AND D.SC_CD='&&SC_CD'
AND B.SC_CD='&&SC_CD'
AND B.RTN_DT BETWEEN '&&DATE1' AND '&&DATE2'
AND B.CANCL IS NULL
GROUP BY A.CAT_CD,A.PRD_CD
UNION
SELECT DISTINCT A.CAT_CD,A.PRD_CD,0 BILL_QTY,0 RTN_QTY,0 BONUS_QNT,SUM(A.RV_QTY)RV_QTY FROM 
INV.FG_RV2 A,INV.FG_RV1 B WHERE B.LOC_CD='&&SC_CD'
AND A.LOC_CD='&&SC_CD' AND A.RV_NO=B.RV_NO
AND RV_TYPE IN('24','04') AND A.TYP_CD='09'
AND RV_TYPE NOT IN('13','19','18','78')
AND RV_DT BETWEEN '&&DATE1' AND '&&DATE2'
GROUP BY A.CAT_CD,A.PRD_CD
/

CREATE TABLE K_BONUS_RV AS
SELECT DISTINCT A.CAT_CD,A.PRD_CD,SUM(A.BILL_QTY)BILL_QTY,SUM(A.RTN_QTY)RTN_QTY,SUM(BONUS_QNT)BONUS_QNT,0 RV_QTY FROM BONUS_RV A,
INV.FG_RV2 B,
INV.FG_RV1 C
WHERE B.LOC_CD='&&SC_CD'
AND C.LOC_CD='&&SC_CD'
AND A.CAT_CD=B.CAT_CD
AND A.PRD_CD=B.PRD_CD
AND C.RV_NO=B.RV_NO
AND RV_TYPE='04'
AND B.TYP_CD='09'
AND RV_TYPE NOT IN('13','19','18','78')
AND RV_DT BETWEEN '&&DATE1' AND '&&DATE2'
--------------AND B.RV_NO IN(SELECT RV_NO FROM INV.FG_RV1 WHERE LOC_CD='&&SC_CD' AND RV_TYPE='04' AND RV_DT BETWEEN '&&DATE1' AND '&&DATE2')
GROUP BY A.CAT_CD,A.PRD_CD
UNION
SELECT DISTINCT A.CAT_CD,A.PRD_CD,0 BILL_QTY,0 RTN_QTY,0 BONUS_QNT,SUM(B.RV_QTY)RV_QTY FROM BONUS_RV A,
INV.FG_RV2 B,
INV.FG_RV1 C
WHERE B.LOC_CD='&&SC_CD'
AND C.LOC_CD='&&SC_CD'
AND A.CAT_CD=B.CAT_CD
AND A.PRD_CD=B.PRD_CD
AND C.RV_NO=B.RV_NO
AND RV_TYPE='04'
AND B.TYP_CD='09'
AND RV_TYPE NOT IN('13','19','18','78')
AND RV_DT BETWEEN '&&DATE1' AND '&&DATE2'
--------------------AND B.RV_NO IN(SELECT RV_NO FROM INV.FG_RV1 WHERE LOC_CD='&&SC_CD' AND RV_TYPE='04' AND RV_DT BETWEEN '&&DATE1' AND '&&DATE2')
GROUP BY A.CAT_CD,A.PRD_CD

SET VER OFF

SET LINES 100

SELECT DISTINCT DIV_CD,A.CAT_CD,A.PRD_CD,SUBSTR((PROD_NM),1,35)PROD_NAME,SUM(BILL_QTY)BILL_QTY,SUM(RTN_QTY)RTN_QTY,SUM(BONUS_QNT)CALB_QNT,SUM(RV_QTY)RV_QTY,SUM(BONUS_QNT-RV_QTY) DIFF
FROM K_BONUS_RV A,SCENT.INV_PROD B
WHERE A.CAT_CD=B.CAT_CD
AND A.PRD_CD=B.PRD_CD
AND B.TYP_CD='09'
GROUP BY DIV_CD,A.CAT_CD,A.PRD_CD,PROD_NM
HAVING SUM(BONUS_QNT-RV_QTY)>'0'
ORDER BY DIV_CD, DIFF, A.CAT_CD,A.PRD_CD
/
DROP TABLE BONUS_RV PURGE;
DROP TABLE K_BONUS_RV PURGE;


SPOOL OFF
ED ON.LST
