SPOOL ON
SET VER OFF
SET PAGES 500
SET LIN 500
ACCEPT DT1 CHAR PROMPT 'CURRENT MONTH START DATE (HUMAN):'
ACCEPT DT2 CHAR PROMPT 'TODAYS DATE : '
ACCEPT SC CHAR PROMPT 'SALES CENTER:'

CREATE TABLE BON_RTN AS
SELECT M.FL_MVH,M.FP_ID,M.BILL_NO,D.CAT_CD||D.PRD_CD CODE,D.PRO_QTY,D.GIFT_FL,S.BONUS_QNT,M.DELI_DT,M.BILL_DT,
(SELECT NVL(SUM(RD.RTN_QTY),0) FROM SCENT.RTN_DET RD WHERE RD.SC_CD='&&SC' AND RTN_NO IN(SELECT RM.RTN_NO FROM SCENT.RTN_MAS RM WHERE RM.SC_CD='&&SC'  AND  RM.RTN_DT BETWEEN '&DT1' AND '&DT2' AND M.BILL_NO=RM.BILL_NO AND RM.CANCL IS NULL) AND D.CAT_CD||D.PRD_CD=RD.CAT_CD||RD.PRD_CD) RTN
--(SELECT NVL(SUM(XD.RTN_QTY),0) FROM SCENT.RTN_DET XD WHERE XD.SC_CD='&&SC' AND XD.RTN_NO IN(SELECT XM.RTN_NO FROM SCENT.RTN_MAS XM WHERE XM.SC_CD='&&SC' AND  XM.RTN_DT BETWEEN '&DT1' AND '&DT2' AND XM.BILL_NO!=XM.BILL_NO AND XM.CANCL IS NULL) AND D.CAT_CD||D.PRD_CD=XD.CAT_CD||XD.PRD_CD) RTN_LATE
FROM SCENT.BILL_MAS M,SCENT.BILL_DET D,SCENT.BONUS_SALE S
WHERE M.SC_CD=D.SC_CD AND S.SC_CD=M.SC_CD
AND M.SC_CD='&&SC' 
AND S.BILL_NO=M.BILL_NO AND S.CAT_CD||S.PRD_CD=D.CAT_CD||D.PRD_CD 
AND M.BILL_NO NOT IN('6723854')
AND M.DELI_DT BETWEEN '&DT1' AND '&DT2' AND M.BILL_NO=D.BILL_NO AND M.CANCL IS NULL
ORDER BY M.FL_MVH,M.BILL_DT,D.CAT_CD||D.PRD_CD
/
SELECT * FROM BON_RTN WHERE RTN>'0';

CREATE TABLE BON_RTN1 AS
SELECT R.FL_MVH,R.CODE,N.PROD_NM,P.TRADE_VAT,SUM(R.PRO_QTY) PRO_QTY,SUM(R.BONUS_QNT) BONUS_QNT,SUM(R.RTN) RTN,
(SELECT NVL(SUM(X.RV_QTY),0) FROM INV.FG_RV2 X WHERE X.LOC_CD='&SC' AND X.RV_NO IN(SELECT Y.RV_NO FROM INV.FG_RV1 Y WHERE Y.LOC_CD='&SC' AND Y.RV_DT BETWEEN '&DT1' AND '&DT2' AND Y.RV_TYPE IN('04','24')) AND X.CAT_CD||X.PRD_CD=R.CODE  AND X.TYP_CD='09') GAIN,
(SELECT NVL(SUM(X.RV_QTY),0) FROM INV.FG_RV2 X WHERE X.LOC_CD='&SC' AND X.RV_NO IN(SELECT Y.RV_NO FROM INV.FG_RV1 Y WHERE Y.LOC_CD='&SC' AND Y.RV_DT BETWEEN '&DT1' AND '&DT2' AND Y.RV_TYPE IN('04','24')) AND X.CAT_CD||X.PRD_CD=R.CODE  AND X.TYP_CD='09')-SUM(R.BONUS_QNT) SHORT
FROM BON_RTN R,SCENT.INV_PROD N,SCENT.PROD_RATE P
WHERE R.RTN<>'0'
AND CODE=N.CAT_CD||N.PRD_CD 
AND CODE=P.CAT_CD||P.PRD_CD
AND P.TYP_CD='09'
AND N.TYP_CD='09'
GROUP BY R.FL_MVH,R.CODE,N.PROD_NM,P.TRADE_VAT
ORDER BY R.FL_MVH,R.CODE,N.PROD_NM,P.TRADE_VAT
/

SELECT * FROM BON_RTN1 WHERE SHORT<'0'
--WHERE PRO_QTY=RTN
/
spool off

DROP TABLE BON_RTN 
/
DROP TABLE BON_RTN1
/
ed on.lst
