SET NUMFORMAT 99999.99

SPOOL ON

SET LINES 130
SET PAGES 500


set ver off

SET LINES 350
SET PAGES 350


SELECT A.CAT_CD,A.PRD_CD,A.B_NO,C.PROD_NM,A.B_NO,B.ISS_FROM,B.RV_DT,B.RV_NO,A.RV_QTY
FROM INV.FG_RV2 A,INV.FG_RV1 B,SCENT.INV_PROD C 
WHERE A.CAT_CD||A.PRD_CD='&PRD_CD' 
AND B.RV_DT BETWEEN '&DT1' AND '&DT2'
AND A.CAT_CD=C.CAT_CD
AND A.PRD_CD=C.PRD_CD
AND C.TYP_CD='09'
AND A.RV_NO=B.RV_NO
AND B.RV_TYPE='04'
AND A.LOC_CD='&SC'
AND A.LOC_CD=B.LOC_CD
GROUP BY A.CAT_CD,A.PRD_CD,B.RV_NO,B.RV_DT,A.RV_QTY,A.B_NO,C.PROD_NM,B.ISS_FROM
ORDER BY A.B_NO
/



SPOOL OFF
ED ON.LST
