
SET VER OFF

SET LINE 40
SET PAGES 20000
COLUMN VALUE FORMAT 99,99,999.99

COMPUTE SUM OF VALUE ON DIV_CD
COMPUTE SUM OF VALUE ON REPORT
BREAK ON REPORT ON DIV_CD

---COMPUTE COUNT OF RTN_NO ON REPORT
---COMPUTE COUNT OF RTN_NO ON FL_MVH



TTITLE center 'Depot:'&&SC_CD', Bonus Gain GRN' SKIP2



SPOOL ON

SELECT A.DIV_CD,A.RV_NO,A.RV_DT,SUM(B.T_VAT*B.RV_QTY)VALUE FROM INV.FG_RV1 A, INV.FG_RV2 B
WHERE A.LOC_CD='&&SC_CD' AND A.LOC_CD=B.LOC_CD AND A.RV_NO=B.RV_NO AND A.RV_TYPE='04' AND A.RV_DT BETWEEN '&Date1' AND '&Date2'
GROUP BY A.DIV_CD,A.RV_NO,A.RV_DT,A.RV_NO
ORDER BY A.DIV_CD,A.RV_DT,A.RV_NO,A.RV_NO
/

 
SPOOL OFF

ED ON.LST