SET LINE 45
SET PAGES 15000

COMPUTE COUNT OF BILL_NO ON REPORT
COMPUTE MAX OF SALE_NET ON FL_MVH
COMPUTE COUNT OF BILL_NO ON FL_MVH
BREAK ON REPORT ON FL_MVH


SPOOL ON

TTITLE center 'Depot:'&&SC_CD', Cancel Bill' SKIP2

SELECT FL_MVH, FP_ID, BILL_NO, SALE_NET, SALE_CD, CANCL_REASON, BILL_DT 
	FROM SCENT.BILL_MAS 
	WHERE SC_CD='&&SC_CD' 
	AND BILL_DT BETWEEN '&DATE1' AND '&DATE2' 
	AND CANCL IS NOT NULL
ORDER BY FL_MVH, SALE_CD, BILL_NO
/


SPOOL OFF

ED ON.LST