COMPUTE SUM OF A.CHQ_AMT ON REPORT
BREAK ON A.CHQ_AMT ON REPORT

SET LINES 180
SET PAGES 300

TTITLE CENTER 'Depot:'&&SC_CD'' SKIP 1 -
CENTER 'Delay Cheque Collection' SKIP 2

SPOOL ON

COLUMN CHQ_AMT FORMAT 99,99,999.99
COLUMN COLL_AMT FORMAT 99,99,999.99



SELECT DISTINCT A.FP_ID,substr(e.emp_nm,1,20) fp_name,D.CL_NM,C.SALE_CD,C.BILL_NO,TO_CHAR(C.DELI_DT,'DD.MM.YY') DELI_DT,C.SALE_NET,A.REF_NO,TO_CHAR(A.REF_DT,'DD.MM.YY') REF_DT,TO_CHAR(A.CHQ_DT,'DD.MM.YY') CHQ_DT,A.CHQ_NO,A.CHQ_AMT,B.COLL_AMT,ROUND(A.REF_DT-A.CHQ_DT) DAYS
FROM SCENT.CHQ_INFO A,SCENT.CHQ_BILL B,SCENT.BILL_MAS C,SCENT.CL_INFO D,pims.emp_mast e
WHERE A.SC_CD=B.SC_CD
AND A.SC_CD=C.SC_CD
AND A.SC_CD=D.SC_CD
AND A.SC_CD='&&SC_CD'
AND a.fp_id=e.emp_id
AND A.REF_NO=B.REF_NO
AND B.BILL_NO=C.BILL_NO
AND A.REF_DT BETWEEN '&DATE1' AND '&DATE2' 
AND C.SALE_CD IN('IC','IM','IN','IP')
AND C.FL_MVH='1'
AND D.DIST_CD=C.DIST_CD
AND D.THA_CD=C.THA_CD
AND D.UN_CD=C.UN_CD
AND D.CL_ID=C.CL_ID
ORDER BY DAYS, D.CL_NM,A.FP_ID
/

SPOOL OFF
ED ON.LST
