

SET LINES 130
SET PAGES 15000


SPOOL ON


SELECT DISTINCT A.BILL_NO, A.SC_CD, A.FP_ID, A.DIST_CD, A.THA_CD, A.UN_CD, A.CL_ID, SUBSTR(RPAD(D.FPBS_NM,'18'),1,18) FPBS_NM, INITCAP(SUBSTR(C.CL_NM,1,18)) CL_NM, SUBSTR(RPAD(C.CL_ADDR,'18'),1,18), C.TEL, A.DELI_DT, A.SALE_NET, A.SALE_CD
	FROM SCENT.BILL_MAS A,SCENT.FP_MGR B,SCENT.CL_INFO C, SCENT.FP_BASE D
	WHERE A.SC_CD='&&SC_CD'AND
	A.DELI_DT BETWEEN '01JAN24' AND '02JAN24' AND
	A.SC_CD=C.SC_CD AND
	A.SC_CD=D.SC_CD AND
	A.FP_ID=B.FP_ID AND
	A.DIST_CD=C.DIST_CD AND
	A.THA_CD=C.THA_CD AND
	A.UN_CD=C.UN_CD AND
	A.CL_ID=C.CL_ID AND 
	A.FL_MVH='1' AND
	A.RMBS_CD=D.RMBS_CD AND
	A.FMBS_CD=D.FMBS_CD AND
	A.FL_MVH=D.FL_MVH AND
	A.SALE_CD IN('WM','WO','RC') 
	ORDER BY CL_NM, A.DIST_CD, A.THA_CD, A.UN_CD, A.CL_ID
/



SPOOL OFF

ED ON.LST



