

SET LINE 140
SET PAGES 20000
COLUMN VALUE FORMAT 99,99,999.99


COMPUTE SUM OF VALUE ON DIV_CD
COMPUTE SUM OF VALUE ON REPORT
BREAK ON REPORT ON DIV_CD

---COMPUTE COUNT OF RTN_NO ON REPORT
---COMPUTE COUNT OF RTN_NO ON FL_MVH



TTITLE center 'Depot:'&&SC_CD', Issue Voucher of Date Expired Medicine' SKIP2



SPOOL ON

SELECT DISTINCT A.LOC_CD,A.DIV_CD,A.FP_ID,A.RV_NO,A.SUB_NO,A.RV_DT,A.RV_TYP,A.CAT_CD||A.PRD_CD,B.PROD_NM,A.MFG_DT,A.EXP_DT,A.B_NO,A.RV_QTY,SUM(A.T_VAT*A.RV_QTY) VALUE
	FROM INV.RECV_SUB A, SCENT.INV_PROD B 
	WHERE A.TYP_CD=B.TYP_CD 
	AND A.CAT_CD=B.CAT_CD 
	AND A.PRD_CD=B.PRD_CD 
	AND A.DIV_CD=B.DIV_CD 
	AND A.IV_NO IN (SELECT IV_NO FROM INV.FG_IV WHERE LOC_CD='31' AND IV_DT BETWEEN '&DATE1' AND '&DATE2') 
	AND A.LOC_CD='&&SC_CD' 
	AND A.DIV_CD IN('1','2')
	AND A.RV_TYP='47' 
	---AND EXP_DT<='01AUG2022'
	GROUP BY A.LOC_CD,A.DIV_CD,A.FP_ID,A.RV_NO,A.SUB_NO,A.RV_DT,A.RV_TYP,A.CAT_CD||A.PRD_CD,A.MFG_DT,A.EXP_DT,A.B_NO,A.RV_QTY,B.PROD_NM
	ORDER BY A.DIV_CD,A.EXP_DT,A.CAT_CD||A.PRD_CD

/

 
SPOOL OFF

ED ON.LST