

SET LINE 100
SET PAGES 20000
COLUMN VALUE FORMAT 99,99,999.99


COMPUTE SUM OF VALUE ON DIV_CD
COMPUTE SUM OF VALUE ON REPORT
BREAK ON REPORT ON DIV_CD

---COMPUTE COUNT OF RTN_NO ON REPORT
---COMPUTE COUNT OF RTN_NO ON FL_MVH



TTITLE center 'Depot:'&&SC_CD', Receive Voucher of Date Expired Medicine' SKIP2



SPOOL ON

SELECT DISTINCT LOC_CD,DIV_CD,FP_ID,RV_NO,SUB_NO,RV_DT,RV_TYP,CAT_CD||PRD_CD,MFG_DT,EXP_DT,B_NO,RV_QTY,SUM(T_VAT*RV_QTY) VALUE
	FROM INV.RECV_SUB WHERE RV_DT BETWEEN '01DEC24' AND '31DEC24' 
	AND LOC_CD='&&SC_CD' 
	AND DIV_CD IN('1','2')
	AND RV_TYP='47' 
	---AND EXP_DT<='01AUG2022'
	GROUP BY LOC_CD,DIV_CD,FP_ID,RV_NO,SUB_NO,RV_DT,RV_TYP,CAT_CD||PRD_CD,MFG_DT,EXP_DT,B_NO,RV_QTY
	ORDER BY DIV_CD,EXP_DT,CAT_CD||PRD_CD

/

 
SPOOL OFF

ED ON.LST