
SET VER OFF


SET LINE 45
SET PAGES 20000
COLUMN EXP_VALUE FORMAT 99,99,999.99



TTITLE center 'Depot:'&&SC_CD', IV of Expired Medicine Month wise' SKIP2



SPOOL ON

SELECT DISTINCT LOC_CD,TO_CHAR(IV_DT, 'YYYY-MM') AS MONTH_YEAR, SUM(T_VAT*IV_QTY) AS EXP_VALUE
	FROM INV.FG_IV 
	WHERE LOC_CD='&&SC_CD'AND 
	TYP_CD='09' AND
  	IV_DT BETWEEN '01APR2024' AND '30APR2025' AND 
	DIV_CD IN('1','2') AND 
	IV_TYPE='47'
	GROUP BY LOC_CD,TO_CHAR(IV_DT, 'YYYY-MM')
	ORDER BY MONTH_YEAR;
 
SPOOL OFF

ED ON.LST
