DROP TABLE SS;

CREATE TABLE SS AS
SELECT DISTINCT A.FP_ID, A.CL_ID, SUBSTR(INITCAP(C.CL_NM),1,20)CL_NM, A.FL_MVH, A.SALE_CD, A.BILL_NO, A.DELI_DT, NVL(SUM(A.SALE_NET),0)BILL_AMNT, (SELECT NVL(SUM(AMNT),0)
FROM SCENT.OUT_DET D WHERE SC_CD='&&SC_CD' AND D.BILL_NO=A.BILL_NO AND MOA='R')RTN, (NVL(SUM(A.SALE_NET),0))-(SELECT (NVL(SUM(AMNT),0))
FROM SCENT.OUT_DET D WHERE SC_CD='&&SC_CD' AND D.BILL_NO=A.BILL_NO AND MOA='R')NET_SALE, TO_DATE(B.OUT_DT)COLLEC_DATE, (SELECT SUM(AMNT)
FROM SCENT.OUT_DET D WHERE SC_CD='&&SC_CD' AND D.BILL_NO=A.BILL_NO AND MOA='C' AND D.OUT_DT BETWEEN '&&DATE1' AND '&&DATE2')COLLEC_AMNT, TO_DATE(B.OUT_DT)-TO_DATE(A.DELI_DT)DAYS
FROM SCENT.BILL_MAS A,
     SCENT.OUT_DET B,
     SCENT.CL_INFO C
WHERE A.SC_CD='&&SC_CD'
  AND A.SC_CD=B.SC_CD
  AND A.SC_CD=C.SC_CD
  AND B.OUT_DT BETWEEN '&&DATE1' AND '&&DATE2'
  AND A.BILL_NO=B.BILL_NO
  AND A.DIST_CD=C.DIST_CD
  AND A.THA_CD=C.THA_CD
  AND A.UN_CD=C.UN_CD
  AND A.CL_ID=C.CL_ID
  AND SEQ=(SELECT MAX(SEQ) FROM SCENT.OUT_DET WHERE A.SC_CD=SC_CD AND A.BILL_NO=BILL_NO AND SC_CD='&&SC_CD') 
GROUP BY A.FP_ID, A.CL_ID,A.FL_MVH, A.SALE_CD, A.BILL_NO, A.DELI_DT, C.CL_NM, B.OUT_DT
HAVING (B.OUT_DT-A.DELI_DT)>'31'
ORDER BY A.FP_ID
/

SET LINES 137
SET PAGES 4000
COL COLLEC_AMNT FORMAT 999,99,99,999.99

COMPUTE SUM OF BILL_AMNT RTN NET_SALE COLLEC_AMNT ON REPORT
COMPUTE COUNT OF BILL_NO ON REPORT
BREAK ON REPORT ON REPORT SKIP-1

TTITLE CENTER 'Depot: '&&SC_CD' ' SKIP 1 -
CENTER 'Delay Collection' SKIP 1 CENTER ''Period :  ''&&DATE1'' -to- ''&&DATE2'' -
RIGHT 'More than Days' SKIP 2


SPOOL ON

SELECT FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, ROUND(SUM(COLLEC_AMNT*100/BILL_AMNT))PER, DAYS
FROM SS 
WHERE SALE_CD IN ('WM','WO','RC') AND FL_MVH='1'
GROUP BY FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, DAYS
ORDER BY DAYS, FP_ID
/

SELECT FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, ROUND(SUM(COLLEC_AMNT*100/BILL_AMNT))PER, DAYS
FROM SS 
WHERE SALE_CD IN ('IM','IC','IN','IP') AND FL_MVH='1' AND DAYS>45 
GROUP BY FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, DAYS
ORDER BY DAYS, FP_ID
/

SELECT FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, ROUND(SUM(COLLEC_AMNT*100/BILL_AMNT))PER, DAYS
FROM SS 
WHERE SALE_CD IN ('WM','WO','RC') AND FL_MVH='2'
GROUP BY FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, DAYS
ORDER BY DAYS, FP_ID
/

SELECT FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, ROUND(SUM(COLLEC_AMNT*100/BILL_AMNT))PER, DAYS
FROM SS 
WHERE SALE_CD IN ('IM','IC','IN','IP') AND FL_MVH='2' AND DAYS>45 
GROUP BY FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, DAYS
ORDER BY DAYS, FP_ID
/

SELECT FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, ROUND(SUM(COLLEC_AMNT*100/BILL_AMNT))PER, DAYS
FROM SS 
WHERE SALE_CD IN ('RS') AND FL_MVH='2' AND DAYS>31 
GROUP BY FP_ID, CL_ID, CL_NM, FL_MVH, SALE_CD, BILL_NO, DELI_DT, BILL_AMNT, RTN, NET_SALE, COLLEC_DATE, COLLEC_AMNT, DAYS
ORDER BY DAYS, FP_ID
/


SPOOL OFF

ED ON.LST

DROP TABLE SS
/
