SET LINES 65
SET PAGES 2000
SET NUMFORMAT 99,99,99,999.99


ACCEPT SC CHAR PROMPT 'SALES CENTER : '

TTITLE CENTER 'DEPOT: '&&SC' Remit and Collection' SKIP2


DROP TABLE DD_CM
/


CREATE TABLE DD_CM AS
SELECT DISTINCT SC_CD, RMT_DT, SUM(RMT_AMT)PAID
 FROM SCENT.REMIT_MAS 
WHERE SC_CD='&&SC' AND RMT_DT>='&FIRST_DATE_OF_THE_PERIOD'
 AND CANCL IS NULL
GROUP BY SC_CD, RMT_DT
/


SPOOL ON 

SELECT R.SC_CD, R.RMT_DT, R.PAID, 
(SELECT NVL(SUM(DOC_AMT),0) FROM DACC.DAY_COLLECT C WHERE C.SC_CD=R.SC_CD AND R.RMT_DT=C.COLL_DT AND C.DOC_TYP NOT IN('09'))COLLECT, 
R.PAID-(SELECT NVL(SUM(DOC_AMT),0) FROM DACC.DAY_COLLECT C WHERE C.SC_CD=R.SC_CD AND R.RMT_DT=C.COLL_DT AND C.DOC_TYP NOT IN('09'))DIFF
FROM DD_CM R
WHERE R.SC_CD='&&SC' 
ORDER BY DIFF, R.RMT_DT
/


DROP TABLE DD_CM
/


SPOOL OFF
ED ON.LST
