SET LINES 92
SET PAGES 4000
SET NUMFORMAT 999999.99


---CAT_CD||PROD_CODE WITHOUT SUM DETAILS BATCH SEPARATELY RETURN
---COMPUT SUM OF VAL ON PRD_CD CAT_CD PETTY
---COMPUTE SUM OF VAL RMT_AMT ON REPORT
---COMPUTE SUM OF STK_QTY RV_QTY1 PETTY ON PRD_CD CAT_CD 
---COMPUTE SUM OF STK_QTY RV_QTY1 PETTY ON REPORT
---BREAK ON REPORT ON CAT_CD SKIP-2
---BREAK ON REPORT ON CAT_CD

BREAK ON REPORT ON B.CAT_CD||B.PRD_CD

TTITLE CENTER 'DEPOT: '&&SC_CD' BATCH WISE STOCK DATE: &CURRENT_DATE ' SKIP2
SPOOL ON 


SELECT DISTINCT B.CAT_CD||B.PRD_CD, SUBSTR(RPAD(C.PROD_NM,'30','-------------'),1,30)NAME, B.B_NO, (B.RV_QTY)RV_QTY1, (B.RV_BAL)STK_QTY, SUM(B.RV_BAL/D.MST_PK)PETTY, (B.RV_QTY-B.RV_BAL) DIFF 
FROM INV.FG_RV1 A, INV.FG_RV2 B, SCENT.INV_PROD C, SCENT.PROD_RATE D 
WHERE A.RV_NO=B.RV_NO AND
A.LOC_CD='&&SC_CD' AND
(B.RV_BAL)>'0' AND
B.CAT_CD=C.CAT_CD AND
B.PRD_CD=C.PRD_CD AND
B.TYP_CD=C.TYP_CD AND
A.LOC_CD=B.LOC_CD AND
B.CAT_CD=D.CAT_CD AND
B.PRD_CD=D.PRD_CD AND
B.TYP_CD=D.TYP_CD AND
A.RV_DT BETWEEN '01-JAN-19' AND '31-DEC-24' AND 
B.CAT_CD>'0' AND
A.DIV_CD='&&DIV_CD' AND 
B.TYP_CD='09' AND 
A.RV_TYPE NOT IN('0')
GROUP BY B.CAT_CD||B.PRD_CD,C.PROD_NM,B.B_NO,B.RV_QTY,B.RV_BAL
---HAVING (B.RV_QTY-B.RV_BAL)>'0'
ORDER BY B.CAT_CD||B.PRD_CD
/
 
SPOOL OFF
ED ON.LST
