

---this file is not work after July 2023
SET LINES 75
set pages 50
col Amount format 99,99,999.99

TTITLE CENTER 'Depot: ...' SKIP 1 -
CENTER 'Fuel Bill' SKIP 2

SPOOL ON


SELECT A.EMP_ID,substr(B.EMP_NM,1,20) Employee_Name,C.AC1,C.AC2,C.AC3,C.AC4,C.AC5,C.VR_DT,C.VR_NO,SUM(C.AMNT) Amount FROM DACC.TRANS_MAS A, DACC.TRANS_DET C, PIMS.EMP_MAST B
WHERE A.LOC_CD='&LOC' AND A.LOC_CD=C.LOC_CD AND A.VR_CD=C.VR_CD AND A.VR_DT=C.VR_DT AND A.SCR_NO=C.SCR_NO AND A.VR_NO=C.VR_NO AND A.VR_DT BETWEEN '&DT1' AND '&DT2' AND A.EMP_ID='&EMP_ID' AND A.EMP_ID=B.EMP_ID AND C.AC1||AC2||AC3||AC4||AC5='4320201'
GROUP BY A.EMP_ID,B.EMP_NM,C.AC1,C.AC2,C.AC3,C.AC4,C.AC5,C.VR_DT,C.VR_NO
ORDER BY A.EMP_ID,B.EMP_NM,C.AC1,C.AC2,C.AC3,C.AC4,C.AC5,C.VR_DT,C.VR_NO
/

SPOOL OFF

ED ON.LST
