

SET LINES 101
SET PAGES 1200


SET VER OFF
BREAK ON REPORT ON CAT_CD
SET NUMFORMAT 9999,99999



SPOOL ON
SELECT CL_NM FROM SCENT.CL_INFO WHERE SC_CD='&&SC_CD' AND DIST_CD||THA_CD||UN_CD||CL_ID ='&&Claint_Info'
/


SELECT SC_CD, A.DIST_CD||THA_CD||UN_CD||CL_ID, A.CAT_CD, A.CAT_CD||A.PRD_CD P_Code, INITCAP(SUBSTR(RPAD(B.PROD_NM,'20'),1,20)) PROD_NM, A.DIS_PCT, A.FLAT_RT,A.REST_PRCENT, A.ST_DT,  A.END_DT, A.CR_DT
	FROM  SCENT.FLAT_RATE_INS A, SCENT.INV_PROD B
	WHERE SC_CD='&&SC_CD'
	AND A.DIST_CD||THA_CD||UN_CD||CL_ID ='&&Claint_Info'
	AND A.DIS_PCT > 3
	AND A.TYP_CD=B.TYP_CD 
	AND A.CAT_CD=B.CAT_CD 
	AND A.PRD_CD=B.PRD_CD 
	ORDER BY P_Code
/



SPOOL OFF

ED ON.LST

