SET VER OFF

SET LINES 175
SET PAGES 5000
COMPUTE COUNT OF PROD_NM ON P_CODE
BREAK ON REPORT ON P_CODE



SPOOL ON

SELECT A.SC_CD, A.FP_ID, A.DIST_CD||A.THA_CD||A.UN_CD||A.CL_ID CL_ID, INITCAP(SUBSTR(C.CL_NM,1,18)) CL_NM, A.BILL_NO, A.DELI_DT, A.SALE_NET, A.SALE_CD, D.CAT_CD||D.PRD_CD P_CODE,
INITCAP(SUBSTR(E.PROD_NM,1,20)) PROD_NM, F.DIS_PCT, D.FLAT_RT BILL_RT, F.FLAT_RT APPV_RT, D.FLAT_RT- F.FLAT_RT DIFF, D.PRO_QTY, D.SALE_GR, D.SALE_NET
	FROM SCENT.BILL_MAS A,SCENT.FP_MGR B,SCENT.CL_INFO C, SCENT.BILL_DET D, SCENT.INV_PROD E, SCENT.FLAT_RATE_INS F
	WHERE A.SC_CD='&&SC_CD'AND
	A.DIST_CD||A.THA_CD||A.UN_CD||A.CL_ID = '&CLIENT_CD' AND
	A.DIST_CD||A.THA_CD||A.UN_CD||A.CL_ID = F.DIST_CD||F.THA_CD||F.UN_CD||F.CL_ID AND
	A.DELI_DT BETWEEN '01JAN24' AND '31DEC24' AND
	A.BILL_NO = D.BILL_NO AND
	A.SC_CD=B.SC_CD AND
	A.SC_CD=C.SC_CD AND
	A.SC_CD=D.SC_CD AND
	A.SC_CD=F.SC_CD AND
	A.FP_ID=B.FP_ID AND
	A.DIST_CD=C.DIST_CD AND
	A.THA_CD=C.THA_CD AND
	A.UN_CD=C.UN_CD AND
	A.CL_ID=C.CL_ID AND 
	A.SALE_CD IN('IC','IM','IN') AND
	A.FL_MVH='1' AND
	D.TYP_CD=E.TYP_CD AND 
	D.CAT_CD=E.CAT_CD AND
	D.PRD_CD=E.PRD_CD AND
	D.TYP_CD=F.TYP_CD AND 
	D.CAT_CD=F.CAT_CD AND
	D.PRD_CD=F.PRD_CD AND
	F.DIS_PCT > '&PCT'
	ORDER BY P_CODE, A.BILL_NO

/



SPOOL OFF

ED ON.LST
