---COMPUTE COUNT OF BILL_NO ON REPORT
COMPUTE COUNT OF BILL_NO ON CL_ID
BREAK ON REPORT ON CL_ID
SET LINE 115
SET PAGES 25000

SPOOL ON

SELECT A.FP_ID, C.DIST_CD||C.THA_CD||C.UN_CD||C.CL_ID CL_ID,C.CL_NM,A.BILL_NO,A.DELI_DT,A.SALE_NET,A.SALE_CD,C.OUT_DAY,C.CREDIT_LIMIT
FROM SCENT.BILL_MAS A,SCENT.FP_MGR B,SCENT.CL_INFO C
WHERE A.SC_CD=B.SC_CD AND
A.SC_CD=C.SC_CD AND
A.FP_ID=B.FP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND 
A.SC_CD='&SC_CD'AND
A.DELI_DT BETWEEN '&DATE1' AND '&DATE2'
AND A.SALE_CD IN('IC','IM','IN') AND A.FL_MVH='1'
ORDER BY C.CL_NM,CL_ID,A.SALE_CD,A.BILL_NO
/

SPOOL OFF

ED ON.LST
