SET VER OFF

SET LINE 40
SET PAGES 20000
COLUMN VALUE FORMAT 99,99,999.99


---COMPUTE SUM OF VALUE ON DIV_CD
---COMPUTE SUM OF VALUE ON REPORT
---BREAK ON REPORT ON DIV_CD

---COMPUTE COUNT OF RTN_NO ON REPORT
---COMPUTE COUNT OF RTN_NO ON FL_MVH



TTITLE center 'Depot:'&&SC_CD', ITS Medicine' SKIP2



SPOOL ON

SELECT DIV_CD,IV_NO,IV_DT,IV_TYPE,ISS_TO,SUM(T_VAT*IV_QTY)VALUE FROM INV.FG_IV WHERE LOC_CD='&&SC_CD' AND ISS_TO NOT IN ('21','24','51')
AND IV_DT BETWEEN '&&DATE1' AND '&&DATE2' AND IV_TYPE='32'
GROUP BY DIV_CD,IV_NO,IV_DT,IV_TYPE,ISS_TO
ORDER BY IV_NO,IV_DT,IV_TYPE,ISS_TO
/

SELECT DIV_CD,IV_NO,IV_DT,IV_TYPE,ISS_TO,SUM(T_VAT*IV_QTY)VALUE FROM INV.FG_IV WHERE LOC_CD='&&SC_CD' AND ISS_TO IN ('21')
AND IV_DT BETWEEN '&&DATE1' AND '&&DATE2' AND IV_TYPE='32' 
GROUP BY DIV_CD,IV_NO,IV_DT,IV_TYPE,ISS_TO
ORDER BY IV_NO,IV_DT,IV_TYPE,ISS_TO

/

 
SPOOL OFF

ED ON.LST