
SET LINE 84
SET PAGES 2500
COLUMN SALE_NET FORMAT 99,99,999.99

COMPUTE COUNT OF BILL_NO ON REPORT
COMPUTE SUM OF SALE_NET ON REPORT
COMPUTE MAX OF SALE_NET ON FL_MVH
COMPUTE COUNT OF BILL_NO ON FL_MVH
BREAK ON REPORT ON FL_MVH


TTITLE center 'Depot:'&&SC_CD', Manual Bill' SKIP2

SPOOL ON

SELECT A.fl_mvh,A.FP_ID,A.BILL_NO,A.DELI_DT,B.CL_NM,A.SALE_CD,A.SALE_NET
	FROM SCENT.BILL_MAS A,SCENT.CL_INFO B
	WHERE A.SC_CD='&&SC_CD'
	AND A.DIST_CD=B.DIST_CD
	AND A.THA_CD=B.THA_CD
	AND A.UN_CD=B.UN_CD
	AND A.CL_ID=B.CL_ID
	AND A.SC_CD=B.SC_CD
	AND A.DELI_DT BETWEEN '&DATE1' AND '&DATE2' 
	AND (USER_CD IS NULL OR USER_CD<>'MB')
	AND A.CANCL IS NULL 
	AND A.SALE_CD NOT IN ('ER')
	ORDER BY A.fl_mvh,A.SALE_CD,A.SALE_NET
/


 
SPOOL OFF

ED ON.LST