---UPDT210524
DROP TABLE SAJIB
/

CREATE TABLE SAJIB AS 
SELECT A.FL_MVH,A.RM_ID,A.FM_ID,A.FP_ID,A.SC_CD,A.DIST_CD,A.THA_CD,A.UN_CD,A.CL_ID,A.PAY_MODE,A.SALE_CD,A.BILL_NO,A.SALE_NET,A.BILL_DT,A.DELI_DT,SUM(B.OUT_AMNT) OUT,TO_DATE('&&LAST_DELI_DATE')-A.DELI_DT DAYS FROM 
SCENT.BILL_MAS A,SCENT.OUT_DET B 
WHERE A.BILL_NO=B.BILL_NO AND A.SC_CD=B.SC_CD AND 
	B.SEQ IN (SELECT MAX(SEQ) FROM SCENT.OUT_DET WHERE BILL_NO=A.BILL_NO AND SC_CD=A.SC_CD AND OUT_DT<='&&LAST_DELI_DATE') AND 
A.DELI_DT<='&&LAST_DELI_DATE' AND A.SC_CD='&&SC_CD' AND A.SC_CD=B.SC_CD 
GROUP BY A.FL_MVH,A.FP_ID,A.RM_ID,A.FM_ID,A.SC_CD,A.DIST_CD,A.THA_CD,A.UN_CD,A.CL_ID,A.BILL_NO,A.BILL_DT,A.DELI_DT,A.PAY_MODE,A.SALE_CD,A.SALE_NET,A.DELI_DT,A.BILL_DT,A.SALE_NET
/
COMMIT;


SET LINES 106
SET PAGES 6000
COL OUT FORMAT 9,99,99,999.99
SET VER OFF

COMPUTE SUM OF OUT ON REPORT
COMPUTE COUNT OF BILL_NO ON REPORT
BREAK ON REPORT SKIP-2

TTITLE CENTER 'DEPOT: '&&SC_CD'.' SKIP 1 -
CENTER 'OUTSTANDING STATEMENT' SKIP 1 CENTER ''AS- ON: '&&LAST_DELI_DATE' -
RIGHT 'MORE THAN DAYS' SKIP 2

SPOOL ON

SELECT DISTINCT A.FP_ID,SUBSTR(D.EMP_NM,1,20) FP_NAME,SUBSTR(C.CL_NM,1,20) CLIENT_NAME,A.SALE_CD,A.BILL_NO,TO_CHAR(A.DELI_DT,'DD.MM.YY') DELI_DT,A.SALE_NET BILL_AMT,A.OUT OUT,A.DAYS 
FROM
SAJIB A, SCENT.FP_MGR B, SCENT.CL_INFO C,PIMS.EMP_MAST D, SCENT.FP_BASE E WHERE
A.FP_ID=D.EMP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND
B.BS_CD=E.FPBS_CD AND
A.SC_CD=E.SC_CD AND
A.FP_ID=B.FP_ID AND
A.FL_MVH=E.FL_MVH AND 
A.OUT>'0' AND
A.DAYS >31 AND
A.PAY_MODE='0' AND
A.FL_MVH='1' AND A.SALE_CD IN('WM','WO','RC') AND A.SC_CD='&SC_CD' AND A.SC_CD=B.SC_CD AND A.SC_CD=C.SC_CD AND A.SC_CD=E.SC_CD AND B.SC_CD=E.SC_CD 
ORDER BY A.DAYS
/

SELECT DISTINCT A.FP_ID,SUBSTR(D.EMP_NM,1,20) FP_NAME,SUBSTR(C.CL_NM,1,20) CLIENT_NAME,A.SALE_CD,A.BILL_NO,TO_CHAR(A.DELI_DT,'DD.MM.YY') DELI_DT,A.SALE_NET BILL_AMT,A.OUT OUT,A.DAYS
FROM
SAJIB A, SCENT.FP_MGR B, SCENT.CL_INFO C,PIMS.EMP_MAST D, SCENT.FP_BASE E WHERE
A.FP_ID=D.EMP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND
B.BS_CD=E.FPBS_CD AND
A.SC_CD=E.SC_CD AND
A.FP_ID=B.FP_ID AND
A.FL_MVH=E.FL_MVH AND 
A.OUT>'0' AND
A.DAYS >5 AND
A.PAY_MODE='1' AND
A.FL_MVH='1' AND A.SALE_CD IN('WM','WO','RC') AND A.SC_CD='&SC_CD' AND A.SC_CD=B.SC_CD AND A.SC_CD=C.SC_CD AND A.SC_CD=E.SC_CD AND B.SC_CD=E.SC_CD 
ORDER BY A.DAYS
/

SELECT DISTINCT A.FP_ID,SUBSTR(D.EMP_NM,1,20) FP_NAME,SUBSTR(C.CL_NM,1,20) CLIENT_NAME,A.SALE_CD,A.BILL_NO,TO_CHAR(A.DELI_DT,'DD.MM.YY') DELI_DT,A.SALE_NET BILL_AMT,A.OUT OUT,A.DAYS
FROM
SAJIB A, SCENT.FP_MGR B, SCENT.CL_INFO C,PIMS.EMP_MAST D, SCENT.FP_BASE E WHERE
A.FP_ID=D.EMP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND
B.BS_CD=E.FPBS_CD AND
A.SC_CD=E.SC_CD AND
A.FP_ID=B.FP_ID AND
A.FL_MVH=E.FL_MVH AND 
A.OUT>'0' AND
A.DAYS >5 AND
A.PAY_MODE='1' AND
A.FL_MVH='2' AND A.SALE_CD IN('WM','WO','RC') AND A.SC_CD='&SC_CD' AND A.SC_CD=B.SC_CD AND A.SC_CD=C.SC_CD AND A.SC_CD=E.SC_CD AND B.SC_CD=E.SC_CD 
ORDER BY A.DAYS
/

SELECT DISTINCT A.FP_ID,SUBSTR(D.EMP_NM,1,20) FP_NAME,SUBSTR(C.CL_NM,1,20) CLIENT_NAME,A.SALE_CD,A.BILL_NO,TO_CHAR(A.DELI_DT,'DD.MM.YY') DELI_DT,A.SALE_NET BILL_AMT,A.OUT OUT,A.DAYS
FROM
SAJIB A, SCENT.FP_MGR B, SCENT.CL_INFO C,PIMS.EMP_MAST D, SCENT.FP_BASE E WHERE
A.FP_ID=D.EMP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND
B.BS_CD=E.FPBS_CD AND
A.SC_CD=E.SC_CD AND
A.FP_ID=B.FP_ID AND
A.FL_MVH=E.FL_MVH AND 
A.OUT>'0' AND
A.DAYS >'45' AND
A.FL_MVH='1' AND A.SALE_CD IN ('IM','IN','IC','IP') AND A.SC_CD='&SC_CD' AND A.SC_CD=B.SC_CD AND A.SC_CD=C.SC_CD AND A.SC_CD=E.SC_CD AND B.SC_CD=E.SC_CD 
ORDER BY A.DAYS
/


SELECT DISTINCT A.FP_ID,SUBSTR(D.EMP_NM,1,20) FP_NAME,SUBSTR(C.CL_NM,1,20) CLIENT_NAME,A.SALE_CD,A.BILL_NO,TO_CHAR(A.DELI_DT,'DD.MM.YY') DELI_DT,A.SALE_NET BILL_AMT,A.OUT OUT,A.DAYS
FROM
SAJIB A, SCENT.FP_MGR B, SCENT.CL_INFO C,PIMS.EMP_MAST D, SCENT.FP_BASE E WHERE
A.FP_ID=D.EMP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND
B.BS_CD=E.FPBS_CD AND
A.SC_CD=E.SC_CD AND
A.FP_ID=B.FP_ID AND
A.FL_MVH=E.FL_MVH AND 
A.OUT>'0' AND
A.DAYS >'45' AND
A.FL_MVH='2' AND A.SALE_CD IN ('IM','IN','IC','IP') AND A.SC_CD='&SC_CD' AND A.SC_CD=B.SC_CD AND A.SC_CD=C.SC_CD AND A.SC_CD=E.SC_CD AND B.SC_CD=E.SC_CD 
ORDER BY A.DAYS
/

SELECT DISTINCT A.FP_ID,SUBSTR(D.EMP_NM,1,20) FP_NAME,SUBSTR(C.CL_NM,1,20) CLIENT_NAME,A.SALE_CD,A.BILL_NO,TO_CHAR(A.DELI_DT,'DD.MM.YY') DELI_DT,A.SALE_NET BILL_AMT,A.OUT OUT,A.DAYS 
FROM
SAJIB A, SCENT.FP_MGR B, SCENT.CL_INFO C,PIMS.EMP_MAST D, SCENT.FP_BASE E WHERE
A.FP_ID=D.EMP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND
B.BS_CD=E.FPBS_CD AND
A.SC_CD=E.SC_CD AND
A.FP_ID=B.FP_ID AND
A.FL_MVH=E.FL_MVH AND 
A.OUT>'0' AND
A.DAYS >31 AND A.FL_MVH='2' AND A.SALE_CD IN('RS') AND A.SC_CD='&SC_CD' AND A.SC_CD=B.SC_CD AND A.SC_CD=C.SC_CD AND A.SC_CD=E.SC_CD AND B.SC_CD=E.SC_CD 
ORDER BY A.DAYS
/



SELECT DISTINCT A.FP_ID,SUBSTR(D.EMP_NM,1,20) FP_NAME,SUBSTR(C.CL_NM,1,20) CLIENT_NAME,A.SALE_CD,A.BILL_NO,TO_CHAR(A.DELI_DT,'DD.MM.YY') DELI_DT,A.SALE_NET BILL_AMT,A.OUT OUT,A.DAYS
FROM
SAJIB A, SCENT.FP_MGR B, SCENT.CL_INFO C,PIMS.EMP_MAST D, SCENT.FP_BASE E WHERE
A.FP_ID=D.EMP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND
B.BS_CD=E.FPBS_CD AND
A.SC_CD=E.SC_CD AND
A.FP_ID=B.FP_ID AND
A.FL_MVH=E.FL_MVH AND 
A.OUT>'0' AND
A.DAYS >7 AND
A.FL_MVH='1' AND A.SALE_CD IN('WS') AND A.SC_CD='&SC_CD' AND A.SC_CD=B.SC_CD AND A.SC_CD=C.SC_CD AND A.SC_CD=E.SC_CD AND B.SC_CD=E.SC_CD 
ORDER BY A.DAYS
/

SELECT DISTINCT A.FP_ID,SUBSTR(D.EMP_NM,1,20) FP_NAME,SUBSTR(C.CL_NM,1,20) CLIENT_NAME,A.SALE_CD,A.BILL_NO,TO_CHAR(A.DELI_DT,'DD.MM.YY') DELI_DT,A.SALE_NET BILL_AMT,A.OUT OUT,A.DAYS
FROM
SAJIB A, SCENT.FP_MGR B, SCENT.CL_INFO C,PIMS.EMP_MAST D, SCENT.FP_BASE E WHERE
A.FP_ID=D.EMP_ID AND
A.DIST_CD=C.DIST_CD AND
A.THA_CD=C.THA_CD AND
A.UN_CD=C.UN_CD AND
A.CL_ID=C.CL_ID AND
B.BS_CD=E.FPBS_CD AND
A.SC_CD=E.SC_CD AND
A.FP_ID=B.FP_ID AND
A.FL_MVH=E.FL_MVH AND 
A.OUT>'0' AND
A.DAYS >7 AND
A.FL_MVH='2' AND A.SALE_CD IN('WS') AND A.SC_CD='&SC_CD' AND A.SC_CD=B.SC_CD AND A.SC_CD=C.SC_CD AND A.SC_CD=E.SC_CD AND B.SC_CD=E.SC_CD 
ORDER BY A.DAYS
/


SPOOL OFF

ED ON.LST

DROP TABLE SAJIB
/
