SPOOL ON
ACCEPT SC CHAR PROMPT 'SALES CENTER :'
ACCEPT DT1 CHAR PROMPT 'AUDIT FIRST DATE :'
ACCEPT DT2 CHAR PROMPT 'AUDIT LAST DATE :'
SET VER OFF
SET NUMFORMAT 99999.99
SET PAGES 5000
SET LIN 300
CREATE TABLE MIS_RATE AS
SELECT DISTINCT I.SC_CD||I.DIST_CD||I.THA_CD||I.UN_CD||I.CL_ID CLIENT,C.CL_NM,C.ICM,I.CAT_CD||I.PRD_CD CODE,I.FLAT_RT,
(SELECT MAX(II.ST_DT) FROM SCENT.FLAT_RATE_INS II WHERE II.SC_CD=I.SC_CD AND I.SC_CD||I.DIST_CD||I.THA_CD||I.UN_CD||I.CL_ID=II.SC_CD||II.DIST_CD||II.THA_CD||II.UN_CD||II.CL_ID) ST_DT,I.DIS_PCT
--(SELECT COUNT(III.DIS_PCT) FROM SCENT.FLAT_RATE_INS III WHERE III.SC_CD=I.SC_CD AND I.SC_CD||I.DIST_CD||I.THA_CD||I.UN_CD||I.CL_ID=III.SC_CD||III.DIST_CD||III.THA_CD||III.UN_CD||III.CL_ID AND I.DIS_PCT=III.DIS_PCT) COUNT
FROM SCENT.FLAT_RATE_INS I,SCENT.CL_INFO C,SCENT.BILL_MAS M
WHERE I.SC_CD='&SC' AND M.SC_CD='&SC' AND C.SC_CD='&SC'
AND C.ICM IN('IC')
--AND M.SALE_CD NOT IN('IM')
--AND M.SALE_CD NOT IN('IC' ,'IM')
AND M.DELI_DT BETWEEN '&DT1' AND '&DT2'
AND I.SC_CD||I.DIST_CD||I.THA_CD||I.UN_CD||I.CL_ID=M.SC_CD||M.DIST_CD||M.THA_CD||M.UN_CD||M.CL_ID
AND I.SC_CD||I.DIST_CD||I.THA_CD||I.UN_CD||I.CL_ID=C.SC_CD||C.DIST_CD||C.THA_CD||C.UN_CD||C.CL_ID
ORDER BY I.SC_CD||I.DIST_CD||I.THA_CD||I.UN_CD||I.CL_ID
/
CREATE TABLE MIS_RATEX AS
SELECT X.CLIENT,X.CL_NM,X.ICM,X.DIS_PCT,X.CODE,N.PROD_NM,X.FLAT_RT,X.ST_DT,
(SELECT sum(P.trade_pr-(trade_pr/100*X.DIS_PCT)+P.vat) FROM SCENT.PROD_RATE P WHERE P.TYP_CD='09' AND X.CODE=P.CAT_CD||P.PRD_CD) ORI,
X.FLAT_RT-(SELECT sum(P.trade_pr-(trade_pr/100*X.DIS_PCT)+P.vat) FROM SCENT.PROD_RATE P WHERE P.TYP_CD='09' AND X.CODE=P.CAT_CD||P.PRD_CD) DIFF
FROM MIS_RATE X,SCENT.INV_PROD N
WHERE N.TYP_CD='09' AND N.CAT_CD||N.PRD_CD=X.CODE
--WHERE COUNT>'150'
ORDER BY CODE
/
CREATE TABLE MIS_RATEXX AS
SELECT X.CLIENT,X.CL_NM,X.ICM,X.CODE,X.PROD_NM,X.DIS_PCT,X.FLAT_RT UPLOAD_RATE,X.ORI TRADE_RATE,X.DIFF DIFFERENCE,X.ST_DT
FROM MIS_RATEX X
WHERE DIFF<'-5'
/
CREATE TABLE MIS_RATEXY AS
SELECT X.CLIENT,X.CL_NM,X.ICM,X.CODE,X.PROD_NM,X.DIS_PCT,X.FLAT_RT UPLOAD_RATE,X.ORI TRADE_RATE,X.DIFF DIFFERENCE,X.ST_DT
FROM MIS_RATEX X
WHERE DIFF>'5'
/
--SELECT * FROM MIS_RATEXX;
--SELECT * FROM MIS_RATEXY;

CREATE TABLE MIS_RATEXz AS
SELECT D.SC_CD,M.FL_MVH,C.CL_NM,D.BILL_NO,M.SALE_CD,M.DELI_DT,D.CAT_CD||D.PRD_CD CODE,X.PROD_NM,X.DIS_PCT,D.PRO_QTY,D.FLAT_RT BILL_RATE,D.SALE_NET,X.UPLOAD_RATE,(X.UPLOAD_RATE-D.FLAT_RT) RATE_DIFF,(X.UPLOAD_RATE-D.FLAT_RT)*PRO_QTY TOTAL_DIFF,TRADE_RATE RT_SHOULD_BE,(TRADE_RATE-D.FLAT_RT)*PRO_QTY WE_LOSS
FROM SCENT.BILL_DET D,SCENT.BILL_MAS M,MIS_RATEXX  X,SCENT.CL_INFO C
WHERE D.SC_CD=M.SC_CD AND C.SC_CD=M.SC_CD 
AND M.SC_CD='&SC'
AND M.BILL_NO=D.BILL_NO
AND X.CLIENT=M.SC_CD||M.DIST_CD||M.THA_CD||M.UN_CD||M.CL_ID
AND D.CAT_CD||D.PRD_CD=X.CODE 
AND CANCL IS NULL
--AND D.CAT_CD NOT IN('05')
--AND D.CAT_CD||PRD_CD NOT IN('171016')
AND M.SC_CD||M.DIST_CD||M.THA_CD||M.UN_CD||M.CL_ID=C.SC_CD||C.DIST_CD||C.THA_CD||C.UN_CD||C.CL_ID
ORDER BY D.CAT_CD||D.PRD_CD,D.BILL_NO
/
SELECT * FROM MIS_RATEXz WHERE WE_LOSS>5 AND DELI_DT>='&DT1'
/
DROP TABLE MIS_RATE
/
DROP TABLE MIS_RATEX
/
DROP TABLE MIS_RATEXX
/
DROP TABLE MIS_RATEXY
/
DROP TABLE MIS_RATEXZ
/
SPOOL OFF
ED ON.LST

--sum(prod_rate.trade_pr-(prod_rate.trade_pr/100*0)+prod_rate.vat) pct_0,

--P.UP_DT