ACCEPT SC_CD CHAR PROMPT 'SC_NO : '
---ACCEPT DIV CHAR PROMPT 'FL_MVH : '

DROP TABLE S1;
CREATE TABLE S1 AS
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, SUM(B.SAM_VAL)JAN,0 FEB,0 MAR,0 APR,0 MAY,0 JUN,0 JUL,0 AUG,0 SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01JAN2025' AND '31JAN2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,SUM(B.SAM_VAL)FEB,0 MAR,0 APR,0 MAY,0 JUN,0 JUL,0 AUG,0 SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01FEB2025' AND '28FEB2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,SUM(B.SAM_VAL)MAR,0 APR,0 MAY,0 JUN,0 JUL,0 AUG,0 SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01MAR2025' AND '31MAR2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,SUM(B.SAM_VAL)APR,0 MAY,0 JUN,0 JUL,0 AUG,0 SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01APR2025' AND '30APR2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,0 APR,SUM(B.SAM_VAL)MAY,0 JUN,0 JUL,0 AUG,0 SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01MAY2025' AND '31MAY2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,0 APR,0 MAY,SUM(B.SAM_VAL)JUN,0 JUL,0 AUG,0 SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01JUN2025' AND '30JUN2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,0 APR,0 MAY,0 JUN,SUM(B.SAM_VAL)JUL,0 AUG,0 SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01JUL2025' AND '31JUL2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,0 APR,0 MAY,0 JUN,0 JUL,SUM(B.SAM_VAL)AUG,0 SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01AUG2025' AND '31AUG2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,0 APR,0 MAY,0 JUN,0 JUL,0 AUG,SUM(B.SAM_VAL)SEP,0 OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01SEP2025' AND '30SEP2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,0 APR,0 MAY,0 JUN,0 JUL,0 AUG,0 SEP,SUM(B.SAM_VAL)OCT,0 NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01OCT2025' AND '30OCT2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,0 APR,0 MAY,0 JUN,0 JUL,0 AUG,0 SEP,0 OCT,SUM(B.SAM_VAL)NOV,0 DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01NOV2025' AND '30NOV2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO
UNION
SELECT DISTINCT C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT,W_DT, SUBSTR((A.REMARKS),1,10) REMARKS, B.BILL_V_NO, 0 JAN,0 FEB,0 MAR,0 APR,0 MAY,0 JUN,0 JUL,0 AUG,0 SEP,0 OCT,0 NOV,SUM(B.SAM_VAL)DEC  
FROM SCENT.SAMP_MAS A, SCENT.SAMP_DET B,SCENT.FP_MGR C, SCENT.INV_PROD D
	WHERE A.SC_NO='&SC_CD'
	AND A.SC_NO=B.SC_NO
	AND A.SC_NO=C.SC_CD
	and a.fl_mvh=C.FL_MVH
	AND C.FL_MVH=D.DIV_CD
	AND A.BILL_v_DT BETWEEN '01DEC2025' AND '31DEC2025'
	AND A.BILL_V_NO=B.BILL_V_NO  
	AND A.FP_ID=C.FP_ID
	AND B.TYP_CD=D.TYP_CD
	AND B.CAT_CD||B.PRD_CD=D.CAT_CD||D.PRD_CD
	AND B.TYP_CD='09'
	AND A.PROM_CAT IN('03','18')
	AND CANCL IS NULL 
	AND C.STATUS NOT IN('P')
group by C.RM_ID, C.FM_ID, a.PROM_CAT, A.FP_ID, A.BILL_V_DT, W_DT, A.REMARKS, B.BILL_V_NO;

COMPUTE SUM OF JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC ON REPORT
COMPUTE SUM OF JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC ON RM_ID
COMPUTE SUM OF JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC ON FM_ID
COMPUTE SUM OF JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC ON FP_ID

BREAK ON REPORT ON RM_ID ON FM_ID ON FP_ID

SET LINES 242
SET PAGES 750 
SET NUMFORMAT 9,99,99,999.99
---COLUMN JAN FORMAT 9,99,999.99
spool on

SELECT RM_ID,FM_ID,PROM_CAT,FP_ID,BILL_V_DT,REMARKS,BILL_V_NO,SUM(JAN)JAN,SUM(FEB)FEB,SUM(MAR)MAR,SUM(APR)APR,SUM(MAY)MAY,SUM(JUN)JUN,SUM(JUL)JUL,SUM(AUG)AUG,SUM(SEP)SEP,SUM(OCT)OCT,SUM(NOV)NOV,SUM(DEC)DEC
FROM S1
GROUP BY RM_ID,FM_ID,PROM_CAT,FP_ID,BILL_V_DT,REMARKS,BILL_V_NO
ORDER BY RM_ID,FM_ID,PROM_CAT,FP_ID,BILL_V_DT,REMARKS,BILL_V_NO
/



COMPUTE SUM OF JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC ON REPORT
BREAK ON REPORT SKIP-3

SELECT RM_ID, SUM(JAN)JAN,SUM(FEB)FEB,SUM(MAR)MAR,SUM(APR)APR,SUM(MAY)MAY,SUM(JUN)JUN,SUM(JUL)JUL,SUM(AUG)AUG,SUM(SEP)SEP,SUM(OCT)OCT,SUM(NOV)NOV,SUM(DEC)DEC
FROM S1
GROUP BY RM_ID
ORDER BY RM_ID

/


SPOOL OFF

ED ON.LST