
SET LINE 55
SET PAGES 20000
COLUMN RTN_NET FORMAT 99,99,999.99

COMPUTE COUNT OF RTN_NO ON REPORT
---COMPUTE SUM OF RTN_NET ON REPORT
COMPUTE MAX OF RTN_NET ON FL_MVH
COMPUTE COUNT OF RTN_NO ON FL_MVH
BREAK ON REPORT ON FL_MVH


TTITLE center 'Depot:'&&SC_CD', Return Bill' SKIP2

SPOOL ON

SELECT SC_CD, FL_MVH, FP_ID, BILL_NO, RTN_NO, RTN_DT,RSN_NO, SALE_CD, RTN_NET 
	FROM SCENT.RTN_MAS 
	WHERE SC_CD='&&SC_CD' 
	AND RTN_DT BETWEEN '&DATE1' AND '&DATE2'
	AND CANCL IS NULL 
	ORDER BY FL_MVH, RTN_NO
/

 
SPOOL OFF

ED ON.LST