
SET LINES 96
SET PAGES 2000
SET NUMFORMAT 9999999999.99



COMPUTE COUNT OF B_NO ON PRD_CD  

BREAK ON REPORT ON PRD_CD  

SPOOL ON

SELECT DISTINCT A.DIV_CD, C.CAT_CD, C.PRD_CD, C.PROD_NM, A.RV_NO, B.B_NO, A.RV_DT, SUM(RV_QTY) RV_QTY, A.ISS_FROM 
---SUM(T_VAT*RV_QTY) T_VAL
FROM INV.FG_RV1 A, INV.FG_RV2 B,SCENT.INV_PROD C
WHERE A.RV_DT>='&RV_DATE_FROM'
AND A.LOC_CD='&SC_CD'
AND A.LOC_CD=B.LOC_CD
AND A.DIV_CD='&DIV'
AND A.RV_NO=B.RV_NO
AND C.CAT_CD=B.CAT_CD
AND C.PRD_CD=B.PRD_CD
AND B.TYP_CD=C.TYP_CD
AND B.TYP_CD='09'
---AND A.ISS_FROM IS NOT NULL
AND B.CAT_CD||B.PRD_CD IN('&PROD','&PROD','&PROD','&PROD','&PROD','&PROD','&PROD','&PROD','&PROD','&PROD','&PROD','&PROD','&PROD','&PROD')
GROUP BY A.DIV_CD, C.CAT_CD, C.PRD_CD, C.PROD_NM, A.RV_NO, B.B_NO, A.RV_DT, RV_QTY, A.ISS_FROM
ORDER BY C.CAT_CD, C.PRD_CD, B.B_NO, A.RV_DT, A.DIV_CD
/

SPOOL OFF
ED ON.LST
