set ver off
SET LINES 96
SET PAGES 2000
SET NUMFORMAT 99999.99

COMPUTE COUNT OF B_NO ON PRD_CD  
BREAK ON REPORT ON PRD_CD  

TTITLE CENTER 'DEPOT: '&&SC_CD', RV' SKIP2

SPOOL ON

SELECT DISTINCT A.DIV_CD, C.CAT_CD, C.PRD_CD, C.PROD_NM, A.RV_NO, B.B_NO, A.RV_DT, SUM(RV_QTY) RV_QTY, A.ISS_FROM 
---SUM(T_VAT*RV_QTY) T_VAL
FROM INV.FG_RV1 A, INV.FG_RV2 B,SCENT.INV_PROD C
WHERE A.LOC_CD='&&SC_CD'
AND A.RV_DT>='&&RV_DATE_FROM'
AND A.LOC_CD=B.LOC_CD
AND A.DIV_CD='1'
AND A.RV_NO=B.RV_NO
AND C.CAT_CD=B.CAT_CD
AND C.PRD_CD=B.PRD_CD
AND B.TYP_CD=C.TYP_CD
AND B.TYP_CD='09'
---AND A.ISS_FROM IS NOT NULL
AND B.CAT_CD||B.PRD_CD IN(&Hu_Batch)
GROUP BY A.DIV_CD, C.CAT_CD, C.PRD_CD, C.PROD_NM, A.RV_NO, B.B_NO, A.RV_DT, RV_QTY, A.ISS_FROM
ORDER BY C.CAT_CD, C.PRD_CD, B.B_NO, A.RV_DT, A.DIV_CD
/


SELECT DISTINCT A.DIV_CD, C.CAT_CD, C.PRD_CD, C.PROD_NM, A.RV_NO, B.B_NO, A.RV_DT, SUM(RV_QTY) RV_QTY, A.ISS_FROM 
---SUM(T_VAT*RV_QTY) T_VAL
FROM INV.FG_RV1 A, INV.FG_RV2 B,SCENT.INV_PROD C
WHERE A.LOC_CD='&&SC_CD'
AND A.RV_DT>='&&RV_DATE_FROM'
AND A.LOC_CD=B.LOC_CD
AND A.DIV_CD='2'
AND A.RV_NO=B.RV_NO
AND C.CAT_CD=B.CAT_CD
AND C.PRD_CD=B.PRD_CD
AND B.TYP_CD=C.TYP_CD
AND B.TYP_CD='09'
---AND A.ISS_FROM IS NOT NULL
AND B.CAT_CD||B.PRD_CD IN(&VTN_Batch)
GROUP BY A.DIV_CD, C.CAT_CD, C.PRD_CD, C.PROD_NM, A.RV_NO, B.B_NO, A.RV_DT, RV_QTY, A.ISS_FROM
ORDER BY C.CAT_CD, C.PRD_CD, B.B_NO, A.RV_DT, A.DIV_CD
/


SPOOL OFF
ED ON.LST
