

SET LINE 62
SET PAGES 20000


COMPUTE COUNT OF PROD_NM ON REPORT

COMPUTE COUNT OF PROD_NM ON CAT_CD
BREAK ON REPORT ON CAT_CD



TTITLE center 'All product price of a depot' SKIP2



SPOOL ON

SELECT B.DIV_CD,A.CAT_CD,A.PRD_CD,B.PROD_NM,A.TRADE_PR FROM SCENT.PROD_RATE A, SCENT.INV_PROD B WHERE A.TYP_CD=B.TYP_CD AND A.CAT_CD=B.CAT_CD AND
A.PRD_CD=B.PRD_CD AND A.TYP_CD='09' AND A.CAT_CD||A.PRD_CD IN (SELECT CAT_CD||PRD_CD FROM SCENT.FLAT_RATE WHERE END_DT IN (SELECT MAX(END_DT) 
FROM SCENT.FLAT_RATE WHERE PRD_CD LIKE '1%'))
ORDER BY B.DIV_CD ASC,A.CAT_CD ASC,A.TRADE_PR DESC;

SELECT B.DIV_CD,A.CAT_CD,A.PRD_CD,B.PROD_NM,A.TRADE_PR FROM SCENT.PROD_RATE A, SCENT.INV_PROD B WHERE A.TYP_CD=B.TYP_CD AND A.CAT_CD=B.CAT_CD AND
A.PRD_CD=B.PRD_CD AND A.TYP_CD='09' AND A.CAT_CD||A.PRD_CD IN (SELECT CAT_CD||PRD_CD FROM SCENT.FLAT_RATE WHERE END_DT IN (SELECT MAX(END_DT) 
FROM SCENT.FLAT_RATE WHERE PRD_CD LIKE '4%'))
ORDER BY B.DIV_CD ASC,A.CAT_CD ASC,A.TRADE_PR DESC;

 
SPOOL OFF

ED ON.LST
